- name: configure frontend
  hosts: frontend
  become: yes
  tasks:
  - name: disable default nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable niginx:1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
     name: nginx
     state: present

  - name: start nginx
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes 

  - name: remove html directory
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: abesnt
    
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download the front code from url
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip the frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: restart  nginx
    ansible.builtin.service:
     name: nginx
     state: restarted
     enabled: yes 

  - name: remove default nginx conf
    ansible.builtin.file:
     path: /etc/nginx/conf.d/default.conf
     state: absent  

  - name: copy custom nginx conf
    ansible.builtin.copy:   
     src: nginx.conf
     dest: /etc/nginx/conf.d/roboshop.conf