- name: mongodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy the mongodb repo
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongodb.repo

  - name: install mongodb 
    ansible.builtin.dnf:
     name: mongodb-org
     state: present